name: SAST (Dev)
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  native_scanner:
    name: Boost Native Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download boost-convert-snyk
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o /tmp/snyk
          chmod +x /tmp/snyk
          /tmp/snyk auth ${{ secrets.SNYK_TOKEN }}

          curl https://assets.build.boostsecurity.io/boost-convert-snyk/dev-convert-snyk -o /tmp/get-convert-snyk
          chmod +x /tmp/get-convert-snyk

          bash /tmp/get-convert-snyk 1.0.0.rc5
      - name: Test cli
        run: |
          cat <<EOF > /tmp/runner
          /tmp/snyk test --json 2>&1 > /tmp/snyk.json
          wc -l /tmp/snyk.json
          cat /tmp/snyk.json | /tmp/boost/convert-snyk/latest/boost-convert-snyk process -
          /tmp/snyk test --json 2>&1 || true | /tmp/boost/convert-snyk/latest/boost-convert-snyk process -
          EOF
          chmod +x /tmp/runner

          /tmp/runner
      - name: BoostSecurity Scanner
        uses: boostsecurityio/boostsec-scanner-github@v3
        with:
          action: scan
          api_endpoint: https://api.dev.boostsec.io
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
      - name: BoostSecurity Scanner
        uses: boostsecurityio/boostsec-scanner-github@v3
        with:
          action: exec
          api_endpoint: https://api.dev.boostsec.io
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          exec_command: /tmp/runner

